# Site settings
title: Taylor Huston
email: taylor.a.huston@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Taylor Huston - Web and Mobile Developer.
  Built with Jekll.
  Hosted on GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.taylorhuston.me" # the base hostname & protocol for your site
twitter_username: taylorhu
github_username:  TaylorHuston

# Build settings
markdown: kramdown
input: GFM
